[build]
  command = "npm install && npm run build"
  publish = "dist/personal-finances-front/browser"

[build.environment]
  NODE_ENV = "production"

[context.production]
  command = "npm install && npm run build"
