[build]
  command = "npm run build"
  functions = "functions/"
  publish = "dist/personal-finances-front"

[build.environment]
  NODE_ENV = "production"

[context.production]
  command = "echo \"export const environment = { production: true, API_URL: '\"$BACKEND_URL\"', firebase: { apiKey: '\"$FIREBASE_API_KEY\"', authDomain: '\"$FIREBASE_AUTH_DOMAIN\"', projectId: '\"$FIREBASE_PROJECT_ID\"', storageBucket: '\"$FIREBASE_STORAGE_BUCKET\"', messagingSenderId: '\"$FIREBASE_MESSAGING_SENDER_ID\"', appId: '\"$FIREBASE_APP_ID\"' } };\" > src/environments/environment.prod.ts && npm run build"
